# backend/schemas/role_style_map.py

SEMANTIC_ROLE_TO_STYLE_KEY = {
    # 题目
    "TITLE_1": "CN_TITLE",
    "TITLE_2": "EN_TITLE",

    # 摘要（中文）
    "CN_ABSTRACT_TITLE": "CN_ABSTRACT_TITLE",
    "CN_ABSTRACT_BODY": "CN_ABSTRACT_BODY",
    "CN_KEYWORDS_TITLE": "CN_KEYWORDS_TITLE",
    "CN_KEYWORDS": "CN_KEYWORDS",

    # 摘要（英文）
    "EN_ABSTRACT_TITLE": "EN_ABSTRACT_TITLE",
    "EN_ABSTRACT_BODY": "EN_ABSTRACT_BODY",
    "EN_KEYWORDS_TITLE": "EN_KEYWORDS_TITLE",
    "EN_KEYWORDS": "EN_KEYWORDS",

    # 正文标题
    "TITLE_1_LEVEL": "HEADING_1",
    "TITLE_2_LEVEL": "HEADING_2",
    "TITLE_3_LEVEL": "HEADING_3",
    "TITLE_4_LEVEL": "HEADING_4",
    "TITLE_5_LEVEL": "HEADING_5",

    # 正文
    "BODY": "BODY_TEXT",

    # 参考文献
    "REFERENCE_TITLE": "REFERENCE_TITLE",
    "REFERENCE_ITEM": "REFERENCE_ITEM",

    # 致谢 / 附录
    "ACK_TITLE": "ACK_TITLE",
    "ACK_BODY": "ACK_BODY",
    "APPENDIX_TITLE": "APPENDIX_TITLE",
    "APPENDIX_BODY": "APPENDIX_BODY",

    # 图表公式
    "FIGURE_TITLE": "FIGURE_TITLE",
    "TABLE_TITLE": "TABLE_TITLE",
    "TABLE_TEXT": "TABLE_TEXT",
    "FORMULA": "FORMULA",
    "FORMULA_NUMBER": "FORMULA_NUMBER",

    # 注释
    "FOOTNOTE_CN": "FOOTNOTE_CN",
    "FOOTNOTE_EN": "FOOTNOTE_EN",
}
